<div class="container ldx-upgrade-container" style="padding: 2rem;">
    <div class="jumbotron">
        <h1>Lodgix Has A New Plugin!</h1>
        <p class="lead">Feature packed and developer friendly,  v2.0 is simple, fast and easy-to-use.</p>
        <p><a class="btn btn-lg btn-primary" href="<?php echo lodgix_plugin_download_link(); ?>" target="_blank" role="button">Get Lodgix 2.0</a></p>
    </div>
    
    <div class="row marketing">
        <div class="col-lg-10 col-lg-offset-1">
            <img class="img-responsive" src="<?php echo plugin_dir_url( __DIR__ ).'assets/sedona-preview.jpg'; ?>" alt="Lodgix Sedona Theme Preview">
        </div>
    </div>

    <hr>

    <h2 class="ldx-upgrade-section-title" style="margin-bottom: 3rem;">Features Include:</h2>

    <div class="ldx-row marketing">
    
        <div class="bs-callout bs-callout-info">
            <h3>Mobile friendly</h3>
            <p>All plugin output will display great on mobile devices.</p>
        </div>

        <div class="bs-callout bs-callout-info">
            <h3>Design Flexibility</h3>
            <p>Any developer knowledgeable in CSS can style all plugin components with ease.  Additionally, there are many styling and function options within the plugin for those customers without a developer.</p>
        </div>
        
        <div class="bs-callout bs-callout-info">
            <h3>Widgets</h3>
            <p>Included are five configurable widgets that can be placed virtually anywhere to highlight and query Lodgix inventory,  suggest alternative properties, display reviews and collect guest inquiries.</p>
        </div>


        <div class="bs-callout bs-callout-info">
            <h3>Support for all major page builders...</h3>
            <p>...including Beaver Builder, Divi, Elementor, Gutenberg and Wordpress Blocks.</p>
        </div>

        <div class="bs-callout bs-callout-info">
            <h3>Sync'd with Lodgix</h3>
            <p>100% sync'd with your Lodgix property inventory.</p>
        </div>

        <div class="bs-callout bs-callout-info">
            <h3>Super fast</h3>
            <p>Search queries and page generation times should be incredibly fast provided the website has a hosting plan with sufficient resources for the number of properties in your inventory.</p>
        </div>
        
    </div>

    <hr>

    <h2 class="ldx-upgrade-section-title">Examples of Output Generated By The Plugin</h2>

    <div class="row marketing" style="margin-bottom: 2rem;">
        <div class="col-lg-6">
            
            <h3>Search / Sort</h3>
            <p><a href="https://blog.lodgix.com/vacation-rentals/" rel="nofollow noopener noreferrer" target="_blank" ><span class="glyphicon glyphicon-link" aria-hidden="true"></span> https://blog.lodgix.com/vacation-rentals/</a></p>

            <h3>Property</h3>
            <p><a href="https://blog.lodgix.com/vacation-rentals/125-w-main-main-floor/" rel="nofollow noopener noreferrer" target="_blank"><span class="glyphicon glyphicon-link" aria-hidden="true"></span> https://blog.lodgix.com/vacation-rentals/125-w-main-main-floor/</a></p>

            <h3>Rentals Search Widget</h3>
            <p><a href="https://blog.lodgix.com/search-widget-example/" rel="nofollow noopener noreferrer" target="_blank" ><span class="glyphicon glyphicon-link" aria-hidden="true"></span> https://blog.lodgix.com/search-widget-example/</a></p>
        </div>

        <div class="col-lg-6">
            <h3>Featured Rentals Widget</h3>
            <p><a href="https://blog.lodgix.com/vacation-rentals/merlot-suite/" rel="nofollow noopener noreferrer" target="_blank" ><span class="glyphicon glyphicon-link" aria-hidden="true"></span> https://blog.lodgix.com/vacation-rentals/merlot-suite/</a></p>

            <h3>Categories Widget</h3>
            <p><a href="https://blog.lodgix.com/categories-widget/" rel="nofollow noopener noreferrer" target="_blank" ><span class="glyphicon glyphicon-link" aria-hidden="true"></span> https://blog.lodgix.com/categories-widget/</a></p>

            <h3>Reviews Widget</h3>
            <p><a href="https://blog.lodgix.com/reviews-widget/" rel="nofollow noopener noreferrer" target="_blank" ><span class="glyphicon glyphicon-link" aria-hidden="true"></span> https://blog.lodgix.com/reviews-widget/</a></p>
        </div>
    </div>

    <hr>

    <h2 class="ldx-upgrade-section-title">Requirements</h2>

    <p><b>THIS PLUGIN REQUIRES A SUBSCRIPTION TO LODGIX.COM</b>. To view pricing and sign-up for a free 30 day trial, please visit:</p>
    
    <p><a href="http://www.lodgix.com/pricing/" rel="nofollow noopener noreferrer" target="_blank"><span class="glyphicon glyphicon-link" aria-hidden="true"></span>www.lodgix.com/pricing/</a></p>
    
    <p>Within the plug-in we've supplied credentials to a Lodgix demo account. Using the demo credentials you can activate the plugin and immediately see how the plug-in would work and look in your Wordpress site without having a Lodgix account.</p>
        
    <p><strong>There are three hosting platforms that on occasion do not work well with the Lodgix plugin:</strong></p>
    
    <ul>
        <li><strong>WPEngine</strong></li>
        <li><strong>BlueHost</strong></li>
        <li><strong>WordPress.com</strong></li>
    </ul>

    <p>Depending on the hosting package, these hosting plans can have limitations placed on them which will cause the Lodgix plugin to not work well - or at all.</p>

    <p>Lodgix will not investigate, research or diagnose hosting related issues when hosted on an unsupported host.</p>

    <p>An example of an economical shared, web hosting plan that works great with the Lodgix plugin is the Smart VPS plan by icdsoft.com:<br>
    <a href="https://www.icdsoft.com/en/hosting/managed-vps"  rel="nofollow noopener noreferrer" target="_blank" ><span class="glyphicon glyphicon-link" aria-hidden="true"></span>https://www.icdsoft.com/en/hosting/managed-vps</a>
    </p>
    
    <h3>Hosting requirements:</h3>
    <ol>
        <li>Running PHP 7.4 or higher</li>
        <li>For accounts with 15 or more properties, 1GB of dedicated ram</li>
        <li>PHP Memory LImit:  512M</li>
    </ol>


    <p class="text-center"><a class="btn btn-lg btn-default" href="/wp-admin/options-general.php?page=lodgix.php" role="button">Continue to v1 settings</a></p>

</div>